### PR TITLE
xfd: Fix nosuchsection in non-wikitext pages

### LINKED ISSUE #226: xfd: 提刪內容模型為javascript時提刪失敗
提刪內容模型為javascript時，會因為不存在section=0而失敗（故未提交到提刪頁），然而模板已經掛上去了

https://t.me/wikipedia_zh_n/1388049 安憶的測試:
安憶的測試

https://t.me/wikipedia_zh_n/1388060 自己的測試:
自己的測試

### PR DESCRIPTION
**Pull request by hamishinyuu**
Fix #226

### CODE REVIEW

File: modules/twinklexfd.js [hunk 1]
```diff
@@ -474,7 +474,7 @@ Twinkle.xfd.callbacks = {
 			// Notification to first contributor
 			var wikipedia_page = new Morebits.wiki.page(mw.config.get('wgPageName'));
 			wikipedia_page.setCallbackParameters(pageobj.getCallbackParameters());
-			if (mw.config.get('wgPageContentModel') !== 'Scribunto') {
+			if (['Scribunto', 'javascript', 'sanitized-css', 'css'].indexOf(mw.config.get('wgPageContentModel')) === -1) {
```
Comment (Xi-Plus) [inline modules/twinklexfd.js:477]: 根據 https://github.com/Xi-Plus/twinkle/issues/226#issuecomment-854267121
```suggestion
			if (mw.config.get('wgPageContentModel') === 'wikitext') {
```
不就好了？

**Review by Xi-Plus — CHANGES_REQUESTED** [review]
